### ISSUE TITLE
Enable RPC Server

### ISSUE THREAD

**Issue by joerosato** [jlopp/bitcoin-core-config-generator#20]
Platform: Linux, Pre-Defined: Defaults

Not sure if this an error with the config generator or with bitcoin-qt. I want to use bitcoin-cli on the command line while bitcoin-qt is running, so I want to set the server=1 flag. 

When I use the generator, turning it OFF explicitly produces the following:

```
# [rpc]
# Accept command line and JSON-RPC commands.
server=0
```
When I turn it on, the only line I see at the end is:

`# All values are currently set to defaults. Config is not needed.`

I assumed this was because server=1 is the default setting, so not needed. But it is needed. Without putting server=1 in the config file the server does not start.

**Comment by jlopp** [comment]
Thanks for the bug report, @joerosato! You're right, the bug is in the config generator. You can see here that the default value in Bitcoin Core for "server" is false: https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L1235

This should be a trivial fix for the config generator; I'll aim to get it done today.

**Comment by jlopp** [comment]
I deployed the bug fix to the github page for the generator - please to a hard refresh and let me know if you still have problems with this toggle.
