### ISSUE TITLE
rpc.rpcport  expected type string

### ISSUE THREAD

**Issue by 0xMimir** [jlopp/bitcoin-core-config-generator#59]
When specifying `RPC PORT` in `RPC API`, and then copying config modal with warning message pops up:
```
rpc.rpcport has value 1000 of type number; expected type string
```
when downloading config this message doesn't pop up.

**Comment by jlopp** [comment]
Hmmmmmmm I was not able to reproduce this, but I did see one possible issue in the default data.json file that was setting the default value to an empty string instead of to the expected value of 8332 so I changed and pushed that in 8d58883

Can you do a hard refresh in your browser / open it in incognito and see if you still get the error?

**Comment by 0xMimir** [comment]
Hard refresh removes but only for first time, but now link to this config only opens same config in new tab, it doesn't copy
