### ISSUE TITLE
Preloaded config - Regtest - Missing regtest=1

### ISSUE THREAD

**Issue by saiy2k** [jlopp/bitcoin-core-config-generator#63]
When I select the preloaded config "Regtest", I expect 'regtest=1' line to be added in the configuration box. But it is not happening.

Is the expectation right? If yes, I can do a PR to fix this.

Thanks.

**Comment by jlopp** [comment]
Hm, you're right that it's not adding the appropriate config line. Though it's also tricky because I think there are multiple ways to declare that config.

Normally, if you select the chain manually I use the "chain=test" or "chain=regtest" declaration.

I see that the preset config json files have testnet=1 and regtest=1. I tried switching them to the chain declaration but it's still not propagating. Something is clearly getting lost in translation when applying the preset json.

**Comment by jlopp** [comment]
Thanks for the report; it should be fixed now.
